#!/usr/bin/python

from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
import glob
from subprocess import *
import string

def parse_events():
    template = """
#define __SCRIBE_EVENT <<Error>>

#define SCRIBE_EVENT(name, ...) \
    {'name': #name, 'type': 'Event', 'fields': [ __VA_ARGS__]},

#define SCRIBE_EVENT_SIZED(name, ...) \
    {'name': #name, 'type': 'EventSized', 'fields': [ __VA_ARGS__]},

#define SCRIBE_EVENT_DIVERGE(name, ...) \
    {'name': #name, 'type': 'EventDiverge', 'fields': [ __VA_ARGS__]},

#define __field(type, name) { 'type': #type, 'name': #name },

[
#include <linux/scribe_events.h>
]
    """
    out = Popen('gcc -E -x c -'.split(), stdin=PIPE, stdout=PIPE).communicate(template)[0]
    events = eval(out)
    for event in events:
        if event['type'] == 'EventDiverge':
            event['name'] = 'diverge_' + event['name']
    return events

def camel_case(str):
    return ''.join(map(lambda e: e[0].upper() + e[1:], str.split('_')))

def gen_event_classes(events):
    out = []
    for event in events:
        class_name = 'Event' + camel_case(event['name'])
        scribe_type = 'scribe_api_events.SCRIBE_EVENT_' + event['name'].upper()
        scribe_struct = 'scribe_api_events.scribe_event_' + event['name']

        out.append('cdef class %s(%s):' % (class_name, event['type']))
        out.append('    native_type = Event.register(%s, %s)' % (class_name, scribe_type))

        for field in event['fields']:

            if 'struct' in field['type']:
                continue

            field_name = field['name']
            if '[' in field_name:
                field_name = field_name.split('[')[0]
                target = 'self.payload'
            else:
                target = '(<%s *>self.event_struct).%s' % (scribe_struct, field_name)

            out.append('    property %s:' % field_name)
            out.append('        def __get__(self):')
            out.append('            return %s' % target)
            out.append('        def __set__(self, value):')
            out.append('            %s = value' % target)
        out.append('')
    return out

def gen_event_api(events):
    out = []
    out.append('cdef extern from "linux/scribe_api.h" nogil:')
    out.append('    enum scribe_event_type:')
    for event in events:
        scribe_type = 'SCRIBE_EVENT_' + event['name'].upper()
        out.append('        %s' % scribe_type)
    for event in events:
        scribe_struct = 'scribe_event_' + event['name']

        out.append('    struct %s:' % scribe_struct)
        if len(event['fields']) == 0:
            out.append('        pass')
        for field in event['fields']:
            field_type = field['type']
            field_type = string.replace(field_type, 'struct ', '')
            field_name = field['name']
            out.append('        %s %s' % (field_type, field_name))
    return out

events = parse_events()
with open('src/scribe/events.pxi', 'w+') as f:
    f.write('# Autogenerated file\n')
    f.write('cimport scribe_api_events\n')
    f.write('\n'.join(gen_event_classes(events)))

with open('src/scribe/scribe_api_events.pxd', 'w+') as f:
    f.write('# Autogenerated file\n')
    f.write('from linux cimport *\n')
    f.write('\n'.join(gen_event_api(events)))


################################################################################

scribe_src = sum((glob.glob('src/scribe/' + ext) \
                 for ext in '*.pyx *.pxd *.pxi'.split()), [])
setup(
    name = 'Scribe',
    description = 'Scribe python bindings',
    author = 'Nicolas Viennot',
    author_email = 'nicolas@viennot.biz',
    cmdclass = {'build_ext': build_ext},
    package_dir = {'': 'src'},
    ext_modules = [Extension('scribe',
                             extra_compile_args = ['-Wall', '-O2'],
                             sources = scribe_src,
                             depends = ['/usr/include/linux/scribe_api.h'],
                             libraries = ['scribe'])],
    scripts=['src/record', 'src/replay', 'src/profiler', 'src/shrink']
)
