#!/usr/bin/python2.6

import scribe
import mmap
from optparse import OptionParser

def main():
    usage = 'usage: %prog [options] log_file'
    desc = 'Display in a human readable format a scribe log file'
    parser = OptionParser(usage=usage, description=desc)

    parser.add_option("-r", "--raw",
                      action="store_false", dest="annotated", default=True,
                      help="Do not annotate the log file: "
                           "display the raw event stream")
    parser.add_option("-p", "--pid", action="append", dest="pids",
                      metavar='PID', type='int',
                      help="Only show the given PID. --pid can be repeated.")
    parser.add_option("-o", "--offset",
                      action="store_true", dest="show_offset", default=False,
                      help="Show the offsets")

    (options, args) = parser.parse_args()
    if not args:
        parser.error('Give me a log file')
    if len(args) > 2:
        parser.error('You have extra arguments')

    if not options.annotated and options.pids:
        parser.error('You cannot filter by pid when parsing in raw format')

    logfile = open(args[0], 'r')
    logfile_map = mmap.mmap(logfile.fileno(), 0, prot=mmap.PROT_READ)
    events = scribe.EventsFromBuffer(logfile_map)

    if options.annotated:
        pids = options.pids
        for info, event in scribe.Annotate(events):
            if pids and not info.pid in options.pids:
                continue
            off_str = ""
            if options.show_offset:
                off_str = "%06x " % info.offset
            print("%s[%02d] %s%s%s" % (off_str, info.pid,
                                   ("", "    ")[info.in_syscall],
                                   "  " * info.res_depth,
                                   event))
    else:
        offset = 0
        for event in events:
            off_str = ""
            if options.show_offset:
                off_str = "%06x " % offset
            print("%s%s" % (off_str, event))
            offset += len(event)

if __name__ == '__main__':
    main()
