#!/usr/bin/python

import scribe
import mmap
from optparse import OptionParser

def main():
    usage = 'usage: %prog [options] log_file'
    desc = 'Display in a human readable format a scribe log file'
    parser = OptionParser(usage=usage, description=desc)

    parser.add_option("-r", "--raw",
                      action="store_false", dest="annotated", default=True,
                      help="Do not annotate the log file: "
                           "display the raw event stream")

    (options, args) = parser.parse_args()
    if not args:
        parser.error('Give me a log file')
    if len(args) > 2:
        parser.error('You have extra arguments')
    logfile = open(args[0], 'r+')

    logfile_map = mmap.mmap(logfile.fileno(), 0)

    if options.annotated:
        for info, event in scribe.AnnotatedEventsFromBuffer(logfile_map):
            print("[%02d] %s%s%s" % (info.pid,
                                   ("", "    ")[info.in_syscall],
                                   "  " * info.res_depth,
                                   event))
    else:
        for event in scribe.EventsFromBuffer(logfile_map):
            print(event)

if __name__ == '__main__':
    main()
